package com.mycompany.proyectoparadigma;

import static java.lang.Integer.parseInt;
import java.util.HashMap;
import java.util.StringTokenizer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author reyes
 */
public class IDE extends javax.swing.JFrame {
    
    int contador = 0;
    String error;
    String mensaje;
    String entrada;
    String salida;
    
    String[] keywords = {"sumar", "restar", "multiplicar", "dividir", "int"};
    String[] aritmetica = {"+", "-", "*", "/", "="};
    
    HashMap<String, Integer> palabrasRervadas = new HashMap<>();
    HashMap<String, String> guardarTokens = new HashMap<>();
    
    public IDE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    private void inicializar(){
        for(String keyword : keywords) {
            palabrasRervadas.put(keyword, 0);
        }
    }
    
    //boton de compilar
    private void obtenerToken(){
        inicializar();
        
        entrada = txtEntrada.getText();
        StringTokenizer token = new StringTokenizer(entrada, ";\n\r");
        while(token.hasMoreTokens()){
            String tokens = token.nextToken();
                String resultado = comparar(tokens);
                
                if(!resultado.equals("Palabra reservada no existe")){
                    //^(int )[\w]{1}( ){1}(=)?(\s\w\s)*[+]?(\s\w)?;$
                    if(resultado.equals("int")){
                        variables(tokens);
                    }else{
                        metodos(tokens);
                    }
                    
                }else{
                    
                }
        }
        
        txtResultado.setText(salida);
        
    }
    
    
    private void metodos(String linea){
        String[] palabraReservada = linea.split(" ");
        
        switch(palabraReservada[0]){
            
            case "sumar" -> {
                int suma = parseInt(palabraReservada[1]) + parseInt(palabraReservada[2]);
                salida = String.valueOf(suma);
                
            }
                
            case "restar" -> {
                
            }
                
            case "multiplicar" -> {
                
            }
            
            case "dividir" -> {
                
            }   
        }
    }
    
    private void variables(String linea){
        
        String[] palabraReservada = linea.split(" ");
    }
    
    
    private String comparar(String token){
        error = "Palabra reservada no existe";
        mensaje = error;
        String palabraReservada = token.split(" ")[0];
        
        palabrasRervadas.forEach((key, value) -> {
            
            if(palabrasRervadas.containsKey(palabraReservada)){
                mensaje = key;
            }
            
        });
        
        return mensaje;
        
        
    }
    
    /*private String buscarKeywords(String linea){
        return linea.split(" ")[0];
   }*/
    
    
    /*private void analizarLexico(){
        
        String token, texto = "";
        entrada = txtEntrada.getText();
        String[] tokens = {"&", "#", ".", ",", "{", "}", "[", "]", "(", ")"};
        String[] keywords = {"imprimir", "cadena", "numero", "principal"};
        String[] aritmetica = {"+", "-", "*", "/", "="};
    }*/
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEntrada = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 80, 30));

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 570, 200));

        txtEntrada.setColumns(20);
        txtEntrada.setRows(5);
        jScrollPane2.setViewportView(txtEntrada);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 420, 100));

        jButton2.setText("Compilar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 80, 30));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        obtenerToken();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtEntrada;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
